In [4]:
import matplotlib.pyplot as plt
import numpy as np

In [150]:
def print_test(test):
    for row in test:
        print(row)

test = np.zeros((24, 24))
height, width = test.shape
num_threads = 8
t_h  = (width//(width//num_threads+1))//2
t_w = 2*t_h
t_h, t_w, width//9, 1080//120, 9//2, 1080//6

(3, 6, 2, 9, 4, 180)

In [151]:
for x in range(height//t_h):
    for i in range(width//(t_w)+1):
        for j in range(t_h):
            y = x*t_h + j
            x_1 = t_w*i + j
            if x_1 < 0:
                x_1 = 0
            x_2 = t_w*i + t_w - j
            if x_2 > width:
                x_2 = width
            for k in range(x_1, x_2):
                test[y, k] = 1
            #print(j+(x*4), j+(8*i), 8+(8*i)-j)
            #test[y, x_1:x_2] = 1
print_test(test)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0.]
[0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0.]
[0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0.]
[0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0.]
[0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0

In [152]:

for x in range(height//t_h): # stripe idx
    for i in range(width//(t_w)+1): # amount of triangles
        for j in range(1, t_h): # row in triangle
            y = x*t_h + j 
            x_1 = t_w*i - j
            if x_1 < 0:
                x_1 = 0
            x_2 = t_w*i + j
            if x_2 > width:
                x_2 = width
            for k in range(x_1, x_2):
                test[y, k] = 2
            #test[y, x_1:x_2] = 2
print_test(test)
# y   = 1, 2, 3
# x_1 = 0, 0, 0 <- this is cuz of the range 15, 14, 13
# x_2 = 1, 2, 3 -> *8-2*row

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2.]
[2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2.]
[2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2.]
[2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2.]
[2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2. 2. 2. 1. 1. 2. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 2

In [135]:
test[1][:10]

array([2., 1., 1., 1., 1., 2., 2., 1., 1., 1.])

In [136]:
t_h, t_w

(3, 6)